version: 2


sphinx:
  configuration: docs/source/conf.py

#mkdocs:
#  configuration: mkdocs.yml
#  fail_on_warning: false

formats:
  - epub
  - htmlzip

python:
  version: 2.7
  install:
    - requirements: docs/requirements.txt
  system_packages: true
